
//   ==========================================================================
//   PROJETO: Simulador de Índice de Perda (Fundo Garantidor de Crédito)
//   DOCUMENTAÇÃO DE MEDIDAS DAX (DADOS ANONIMIZADOS)
//   ==========================================================================


// ============================================================================
// 01. MEDIDA: dt_intv_infr
// DESCRIÇÃO: Cálculo do intervalo de datas (janela dos últimos 60 meses) com 
//            base na última operação do banco selecionado anonimizado.
// ============================================================================

  dt_intv_infr = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
RETURN
IF(
    vBancoSelecionado, 
    VAR vUltimaDataOp = CALCULATE(MAX(operacoes[OPE_DATAINICIO]))
    VAR vDataFim = IF(NOT ISBLANK(vUltimaDataOp), EOMONTH(vUltimaDataOp, 0))
    VAR vDataInicio = IF(NOT ISBLANK(vDataFim), EDATE(vDataFim, -60) + 1)
    RETURN
    IF(
        ISBLANK(vDataFim), 
        "-", 
        FORMAT(vDataInicio, "dd/mm/yyyy") & " a " & FORMAT(vDataFim, "dd/mm/yyyy")
    ),
    "-"
)

    
// ============================================================================
// 02. MEDIDA: vlr-garantido
// DESCRIÇÃO:  
//            
// ============================================================================

vlr-garantido = 
CALCULATE(
    SUM(OPERACOES[OPE_VALORGARANTIA]),
        FILTER(
        OPERACOES,
        NOT(
            OPERACOES[OPE_CODIGOSITUACAO-SIT_COD_N3] IN {12, 14, 15} 
            )
        ))

// ============================================================================
// 03. MEDIDA: vlr-garantido_60meses
// DESCRIÇÃO:  
//
// ============================================================================

vlr-garantido_60meses = 
VAR DataFinal = EOMONTH(MAX(dCalendario[Date]),0)
VAR DataInicial = EOMONTH(DataFinal,-60)+1

RETURN
    CALCULATE(
        [vlr-garantido],
            dCalendario[Date] >= DataInicial && dCalendario[Date] <= DataFinal
    )

// ============================================================================
// 04. MEDIDA: media-garantia_60meses
// DESCRIÇÃO:  
//            
// ============================================================================

media-garantia_60meses = [vlr-garantido_60meses] / 60

// ============================================================================
// 05. MEDIDA: vlr-honrado
// DESCRIÇÃO:  
//            
// ============================================================================

vlr-honrado = 
CALCULATE(
    SUM(OPERACOES[OPE_VALOREFETIVOHONRA]),
    USERELATIONSHIP(
        dCalendario[Date],
        OPERACOES[OPE_DATAEFETIVAHONRA]
    ),
    not (OPERACOES[OPE_CODIGOSITUACAO-SIT_COD_N3] IN {12, 14, 15} //Cancelados (12); Transf. de Agência (14); Renegociada (15) )
            )
)

// ============================================================================
// 06. MEDIDA: vlr-honrado_60meses
// DESCRIÇÃO:  
//            
// ============================================================================

vlr-honrado_60meses = 
VAR DataFinal = EOMONTH(MAX(dCalendario[Date]),0)
VAR DataInicial = EOMONTH(DataFinal,-60)+1

RETURN
    CALCULATE (
        [vlr-honrado],
        USERELATIONSHIP(
            dCalendario[Date],
            OPERACOES[OPE_DATAEFETIVAHONRA]
        ),
        DATESBETWEEN ( dCalendario[Date], DataInicial, DataFinal )
    )

// ============================================================================
// 07. MEDIDA: media-honra_60 meses
// DESCRIÇÃO:  
//            
// ============================================================================

media-honra_60 meses = [vlr-honrado_60meses] / 60

// ============================================================================
// 08. MEDIDA: vlr-recuperacao
// DESCRIÇÃO:  
//            
// ============================================================================

vlr-recuperado = CALCULATE(
    SUM(VALOR_RECUPERADO[VLRRECUPERADO]),
    USERELATIONSHIP(
        dCalendario[Date],
        VALOR_RECUPERADO[EXT_DATALANCAMENTO]
    ),
     NOT(
            OPERACOES[OPE_CODIGOSITUACAO-SIT_COD_N3] IN {12, 14, 15} 
            ))

// ============================================================================
// 09. MEDIDA: vlr-recuperado_60meses
// DESCRIÇÃO:  
//            
// ============================================================================

vlr-recuperado_60meses = 
VAR DataFinal = EOMONTH(MAX(dCalendario[Date]),0)
VAR DataInicial = EOMONTH(DataFinal,-60)+1

RETURN
    CALCULATE(
        SUM(
            VALOR_RECUPERADO[VLRRECUPERADO]
        ),
        USERELATIONSHIP(
            dCalendario[Date],
            VALOR_RECUPERADO[EXT_DATALANCAMENTO]
        ),
        DATESBETWEEN ( dCalendario[Date], DataInicial, DataFinal ),
     NOT(
            OPERACOES[OPE_CODIGOSITUACAO-SIT_COD_N3] IN {12, 14, 15} //Cancelados (12); Transf. de Agência (14); Renegociada (15)
            ))

// ============================================================================
// 10. MEDIDA: media-recuperacao_60 meses
// DESCRIÇÃO:  
//            
// ============================================================================

media-recuperacao_60 meses

// ============================================================================
// 11. PARÂMETRO: Simu_Garantia_Mensal
//     MEDIDA: Valor Simu_Garantia_Mensal = SELECTEDVALUE('Simu_Garantia_Mensal'[Simu_Garantia_Mensal], 0)
// DESCRIÇÃO: 
//            
// ============================================================================

// ============================================================================
// 12. PARÂMETRO: Simu_Honra_Mensal = GENERATESERIES(0, 10000000, 10000)
//     MEDIDA: Valor Simu_Honra_Mensal = SELECTEDVALUE('Simu_Honra_Mensal'[Simu_Honra_Mensal], 0)
// DESCRIÇÃO: 
//            
// ============================================================================

// ============================================================================
// 13. PARÂMETRO: Simu_Recupe_Mensal = GENERATESERIES(0, 500000, 5000)
//     MEDIDA: Valor Simu_Recupe_Mensal = SELECTEDVALUE('Simu_Recupe_Mensal'[Simu_Recupe_Mensal], 0)
// DESCRIÇÃO: 
//            
// ============================================================================

// ============================================================================
// 14. MEDIDA: index_IP
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP = ([vlr-honrado_60meses]-[vlr-recuperado_60meses]) / [vlr-garantido_60meses]

// ============================================================================
// 15. MEDIDA: StopLoss_Dinamico_Hibrido
// DESCRIÇÃO: 
//            
// ============================================================================

StopLoss_Dinamico_Hibrido = 
// 1. Capturamos o que está selecionado no segmentador
VAR vBancoSelecionado = SELECTEDVALUE(BANCOS[BCO_NOME_ANONIMO])

// 2. Criamos uma condição para saber se o usuário escolheu um banco válido
// (Não pode ser vazio e não pode estar sem seleção)
VAR vTemSelecaoReal = NOT ISBLANK(vBancoSelecionado)

RETURN
IF(
    vTemSelecaoReal,
    
    // CASO 1: Usuário selecionou um banco específico
    MAX('Serie_Historica_STOPLOSS IF'[STOP LOSS]),
    
    // CASO 2: Nada selecionado (Visão Geral)
        CALCULATE(
        MAX('Serie_Historica_STOPLOSS GERAL'[STOPLOSS]),
        ALL(bancos) // Garante que a tabela Geral ignore qualquer tentativa de filtro de banco
    )
)

// ============================================================================
// 16. MEDIDA: IP_Linha_Tendencia
// DESCRIÇÃO: 
//            
// ============================================================================

IP_Linha_Tendencia = 
// 1. Verifica se há um banco selecionado (evita mostrar média de vários bancos que não faz sentido)
VAR vBancoSelecionado = HASONEVALUE(bancos[BCO_NOME_ANONIMO])

// 2. Verifica se houve entrada nos parâmetros
VAR vSomaParametros = 
    [Valor Simu_Honra_Mensal] + 
    [Valor Simu_Recupe_Mensal] + 
    [Valor Simu_Garantia_Mensal]

VAR vCenario = SELECTEDVALUE('Tabela_Tendencia-SIMULADOR'[Cenário])

RETURN
IF(
    vBancoSelecionado, 
    // Se tiver banco selecionado, executa a lógica da linha
    IF(
        vSomaParametros = 0 && vCenario <> "Atual", 
        BLANK(),
        SWITCH( vCenario,
        "Atual", [index-IP],
        "Mês +1", [index_IP_simulado-1],
        "Mês +2", [index_IP_simulado-2],
        "Mês +3", [index_IP_simulado-3],
        "Mês +4", [index_IP_simulado-4],
        "Mês +5", [index_IP_simulado-5],
        "Mês +6", [index_IP_simulado-6],
        "Mês +7", [index_IP_simulado-7],
        "Mês +8", [index_IP_simulado-8],
            BLANK()
        )
    ),
    // Se não houver banco selecionado, retorna vazio (opcional: pode mostrar o IP Geral se preferir)
    BLANK() 
)


// ============================================================================
// 17. MEDIDA: index_IP_simulado-1
// DESCRIÇÃO: 
//            
// ============================================================================


index_IP_simulado-1 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 0) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 1)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 1)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 1) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-2
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-2 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 1) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 2)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 2)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 2) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-3
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-3 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 2) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 3)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 3)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 3) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-4
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-4 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 3) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 4)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 4)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 4) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-5
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-5 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 4) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 5)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 5)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 5) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-6
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-6 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 5) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 6)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 6)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 6) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-7
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-7 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 6) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 7)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 7)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 7) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 17. MEDIDA: index_IP_simulado-8
// DESCRIÇÃO: 
//            
// ============================================================================

index_IP_simulado-8 = 
VAR vBancoSelecionado = HASONEVALUE(BANCOS[BCO_NOME_ANONIMO])
VAR vDataCorte = [dt_corte]
VAR vDataMesExpurgo = EDATE(DATE(YEAR(vDataCorte), MONTH(vDataCorte), 1), -59)
VAR vInicioExpurgo = vDataMesExpurgo
VAR vFimExpurgo = EOMONTH(vDataMesExpurgo, 7) // Mudar para 1, 2, 3 nas próximas

// Expurgos (Saídas reais do sistema)
VAR vHonraSair = CALCULATE(SUM(operacoes[OPE_VALOREFETIVOHONRA]), operacoes[OPE_DATAEFETIVAHONRA] >= vInicioExpurgo, operacoes[OPE_DATAEFETIVAHONRA] <= vFimExpurgo)
VAR vRecupSair = CALCULATE(SUM(VALOR_RECUPERADO[VLRRECUPERADO]), VALOR_RECUPERADO[EXT_DATALANCAMENTO] >= vInicioExpurgo, VALOR_RECUPERADO[EXT_DATALANCAMENTO] <= vFimExpurgo)
VAR vGarantiaSair = CALCULATE(SUM(operacoes[OPE_VALORGARANTIA]), operacoes[OPE_DATAINICIO] >= vInicioExpurgo, operacoes[OPE_DATAINICIO] <= vFimExpurgo)

// Projeções (Entradas 100% garantidas)
VAR vNovoHonrado = ([vlr-honrado_60meses] - vHonraSair) + ([Valor Simu_Honra_Mensal] * 8)
VAR vNovoRecuperado = ([vlr-recuperado_60meses] - vRecupSair) + ([Valor Simu_Recupe_Mensal] * 8)
VAR vNovoGarantido = ([vlr-garantido_60meses] - vGarantiaSair) + ([Valor Simu_Garantia_Mensal] * 8) // Multiplicar por 2, 3, 4 conforme o mês

VAR vResultado = DIVIDE(vNovoHonrado - vNovoRecuperado, vNovoGarantido, 0)

RETURN
IF(vBancoSelecionado && NOT ISBLANK(vDataCorte), vResultado, "-")


// ============================================================================
// 22. MEDIDA: Titulo_Grafico_Historico
// DESCRIÇÃO: 
//            
// ============================================================================

Titulo_Grafico_Historico = 
// 1. Capturamos o nome do banco selecionado
VAR vBanco = SELECTEDVALUE(BANCOS[BCO_NOME_ANONIMO])

RETURN
IF(
    ISBLANK(vBanco),
    // Caso não tenha seleção (ou seja o "vazio" que corrigimos)
    "Histórico Índice de Perda - FUNDO",
    
    // Caso tenha um banco selecionado (concatenamos o texto com o nome)
    "Histórico Índice de Perda - " & vBanco
)


// ============================================================================
// 23. MEDIDA: Titulo_Grafico_Simulacao
// DESCRIÇÃO: 
//            
// ============================================================================

Titulo_Grafico_Simulacao = 
IF(
    [Valor Simu_Honra_Mensal] + [Valor Simu_Recupe_Mensal] + [Valor Simu_Garantia_Mensal] = 0,
    "Aguardando Parâmetros para Projeção do Índice de Perda...",
    "Tendência do Índice de Perda (Próximos 8 meses)"
)


// ============================================================================
// 24. MEDIDA: dt_corte
// DESCRIÇÃO: 
//            
// ============================================================================

dt_corte = 
VAR vUltimaGarantia = CALCULATE(MAX(operacoes[OPE_DATAINICIO]), ALL(operacoes))
VAR vUltimaHonra = CALCULATE(MAX(operacoes[OPE_DATAEFETIVAHONRA]), ALL(operacoes))
VAR vUltimaRecup = CALCULATE(MAX(VALOR_RECUPERADO[EXT_DATALANCAMENTO]), ALL(VALOR_RECUPERADO[VLRRECUPERADO]))

// Retorna o menor entre os três, garantindo que todos tenham dados até ali
VAR vDataMinimaDasMaximas = MINX({vUltimaGarantia, vUltimaHonra, vUltimaRecup}, [Value])

// Retorna o último dia do mês dessa data
RETURN EOMONTH(vDataMinimaDasMaximas, 0)


